language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpcs --standard=vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2/ --extensions=php Builder/ DependencyInjection/ EventListener/ Logger/
    - ./vendor/bin/phpunit -c phpunit.xml
